[project]
repository-type = "tooling"
versioning-scheme = "semver"
branching-model = "library-release"
release-model = "tagged-release"
primary-language = "python"

[publish]
release = true
docs = true
consumer-refresh = """\
uv tool install --python 3.14 'vergil-tooling @ git+https://github.com/vergil-project/vergil-tooling@v<VERSION>'
"""

[ci]
versions = ["3.12", "3.13", "3.14"]
integration-tests = false

[dependencies]
vergil = "v2.0.7"
