"""Tests for vergil_tooling.lib.pr_template."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from vergil_tooling.lib.pr_template import (
    TemplateError,
    delete_template,
    read_template,
    write_template,
)

if TYPE_CHECKING:
    from pathlib import Path


def _write(tmp_path: Path, text: str) -> None:
    vergil = tmp_path / ".vergil"
    vergil.mkdir(exist_ok=True)
    (vergil / "pr-template.yml").write_text(text)


class TestParseAndRead:
    def test_reads_simple_fields(self, tmp_path: Path) -> None:
        _write(
            tmp_path,
            "issue: 42\n"
            "title: 'fix: bug'\n"
            "summary: Fix the bug\n"
            "linkage: Ref\n"
            "notes: Tested on macOS\n",
        )
        result = read_template(tmp_path)
        assert result["issue"] == "42"
        assert result["title"] == "fix: bug"
        assert result["summary"] == "Fix the bug"
        assert result["linkage"] == "Ref"
        assert result["notes"] == "Tested on macOS"

    def test_reads_double_quoted_values(self, tmp_path: Path) -> None:
        _write(
            tmp_path,
            "issue: 42\n"
            'title: "feat(perms): restrict agent writes"\n'
            "summary: Restrict writes\n"
            "notes: Manual check\n",
        )
        result = read_template(tmp_path)
        assert result["title"] == "feat(perms): restrict agent writes"

    def test_reads_multiline_block(self, tmp_path: Path) -> None:
        _write(
            tmp_path,
            "issue: 42\ntitle: fix\nsummary: |\n  Line one\n  Line two\nlinkage: Ref\nnotes: ok\n",
        )
        result = read_template(tmp_path)
        assert result["summary"] == "Line one\nLine two"

    def test_reads_multiline_block_at_end_of_file(self, tmp_path: Path) -> None:
        _write(
            tmp_path,
            "issue: 42\ntitle: fix\nsummary: Fix\nnotes: |\n  Line one\n  Line two\n",
        )
        result = read_template(tmp_path)
        assert result["notes"] == "Line one\nLine two"

    def test_reads_literal_block_with_chomp_indicator(self, tmp_path: Path) -> None:
        # ``|-`` (strip-chomp) must be treated as a literal block, not parsed as
        # the inline value "|-".
        _write(
            tmp_path,
            "issue: 42\ntitle: fix\nsummary: |-\n  Body line\nnotes: ok\n",
        )
        result = read_template(tmp_path)
        assert result["summary"] == "Body line"

    def test_reads_literal_block_dedents_deeper_indent(self, tmp_path: Path) -> None:
        # A consistent four-space indent must dedent to the content, not leave
        # two stray leading spaces.
        _write(
            tmp_path,
            "issue: 42\ntitle: fix\nsummary: |\n    Line one\n    Line two\nnotes: ok\n",
        )
        result = read_template(tmp_path)
        assert result["summary"] == "Line one\nLine two"

    def test_reads_literal_block_preserves_blank_lines(self, tmp_path: Path) -> None:
        _write(
            tmp_path,
            "issue: 42\ntitle: fix\nsummary: |\n  Para one\n\n  Para two\nnotes: ok\n",
        )
        result = read_template(tmp_path)
        assert result["summary"] == "Para one\n\nPara two"

    def test_skips_lines_without_colon(self, tmp_path: Path) -> None:
        _write(
            tmp_path,
            "issue: 42\nstray line without a colon\ntitle: fix\nsummary: Fix\nnotes: ok\n",
        )
        result = read_template(tmp_path)
        assert result["issue"] == "42"
        assert result["title"] == "fix"

    def test_skips_comment_lines(self, tmp_path: Path) -> None:
        _write(
            tmp_path,
            "# Generated by agent\nissue: 42\ntitle: fix\nsummary: Fix\nnotes: ok\n",
        )
        result = read_template(tmp_path)
        assert result["issue"] == "42"

    def test_raises_when_file_missing(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            read_template(tmp_path)

    def test_raises_when_required_field_missing(self, tmp_path: Path) -> None:
        _write(tmp_path, "issue: 42\ntitle: fix\nnotes: ok\n")
        with pytest.raises(TemplateError, match="summary"):
            read_template(tmp_path)


class TestRequiredNonEmpty:
    def test_raises_when_notes_missing(self, tmp_path: Path) -> None:
        _write(tmp_path, "issue: 42\ntitle: fix\nsummary: Fix\n")
        with pytest.raises(TemplateError, match="notes"):
            read_template(tmp_path)

    def test_raises_when_summary_blank(self, tmp_path: Path) -> None:
        _write(tmp_path, "issue: 42\ntitle: fix\nsummary:   \nnotes: ok\n")
        with pytest.raises(TemplateError, match="summary"):
            read_template(tmp_path)

    def test_raises_when_notes_blank(self, tmp_path: Path) -> None:
        _write(tmp_path, "issue: 42\ntitle: fix\nsummary: Fix\nnotes:   \n")
        with pytest.raises(TemplateError, match="notes"):
            read_template(tmp_path)

    def test_raises_when_literal_block_is_empty(self, tmp_path: Path) -> None:
        # A literal block containing only whitespace collapses to empty and must
        # be rejected (also exercises the no-content-lines dedent path).
        _write(tmp_path, "issue: 42\ntitle: fix\nsummary: |\n   \nnotes: ok\n")
        with pytest.raises(TemplateError, match="summary"):
            read_template(tmp_path)


class TestFoldedScalarRejected:
    @pytest.mark.parametrize("indicator", [">", ">-", ">+"])
    def test_rejects_folded_scalar(self, tmp_path: Path, indicator: str) -> None:
        _write(
            tmp_path,
            f"issue: 42\ntitle: fix\nsummary: {indicator}\n  Folded body text\nnotes: ok\n",
        )
        with pytest.raises(TemplateError, match="folded"):
            read_template(tmp_path)


class TestLinkageValidation:
    @pytest.mark.parametrize("forbidden", ["Closes", "Fixes", "Resolves", "closes", "ref"])
    def test_read_rejects_forbidden_linkage(self, tmp_path: Path, forbidden: str) -> None:
        _write(
            tmp_path,
            f"issue: 42\ntitle: fix\nsummary: Fix\nlinkage: {forbidden}\nnotes: ok\n",
        )
        with pytest.raises(TemplateError, match="linkage"):
            read_template(tmp_path)

    def test_read_error_names_allowed_value(self, tmp_path: Path) -> None:
        _write(tmp_path, "issue: 42\ntitle: fix\nsummary: Fix\nlinkage: Closes\nnotes: ok\n")
        with pytest.raises(TemplateError, match="Ref"):
            read_template(tmp_path)

    def test_read_accepts_absent_linkage(self, tmp_path: Path) -> None:
        _write(tmp_path, "issue: 42\ntitle: fix\nsummary: Fix\nnotes: ok\n")
        result = read_template(tmp_path)
        assert "linkage" not in result

    def test_write_rejects_forbidden_linkage(self, tmp_path: Path) -> None:
        with pytest.raises(TemplateError, match="linkage"):
            write_template(
                tmp_path,
                issue="42",
                title="fix",
                summary="Fix",
                notes="ok",
                linkage="Closes",
            )
        assert not (tmp_path / ".vergil" / "pr-template.yml").exists()


class TestWriteTemplate:
    def test_creates_vergil_dir_and_file(self, tmp_path: Path) -> None:
        path = write_template(
            tmp_path, issue="42", title="fix: bug", summary="Fix the bug", notes="ok"
        )
        assert path.exists()
        content = path.read_text()
        assert "issue:" in content
        assert "42" in content
        assert "fix: bug" in content

    def test_roundtrip(self, tmp_path: Path) -> None:
        write_template(
            tmp_path,
            issue="99",
            title="feat(auth): add token rotation",
            summary="Adds token rotation\nfor the GitHub App.",
            linkage="Ref",
            notes="Tested in staging VM.",
        )
        result = read_template(tmp_path)
        assert result["issue"] == "99"
        assert result["title"] == "feat(auth): add token rotation"
        assert "token rotation" in result["summary"]
        assert result["linkage"] == "Ref"
        assert result["notes"] == "Tested in staging VM."

    def test_warns_on_overwrite(self, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        (vergil / "pr-template.yml").write_text("old content")
        write_template(tmp_path, issue="42", title="fix", summary="Fix", notes="ok")
        err = capsys.readouterr().err
        assert "overwriting" in err.lower()

    def test_default_linkage(self, tmp_path: Path) -> None:
        write_template(tmp_path, issue="42", title="fix", summary="Fix", notes="ok")
        result = read_template(tmp_path)
        assert result["linkage"] == "Ref"

    @pytest.mark.parametrize("field", ["issue", "title", "summary", "notes"])
    def test_write_rejects_empty_required_field(self, tmp_path: Path, field: str) -> None:
        kwargs = {"issue": "42", "title": "fix", "summary": "Fix", "notes": "ok"}
        kwargs[field] = "   "
        with pytest.raises(TemplateError, match=field):
            write_template(tmp_path, **kwargs)
        assert not (tmp_path / ".vergil" / "pr-template.yml").exists()


class TestDeleteTemplate:
    def test_deletes_existing_file(self, tmp_path: Path) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        f = vergil / "pr-template.yml"
        f.write_text("content")
        delete_template(tmp_path)
        assert not f.exists()

    def test_no_error_when_missing(self, tmp_path: Path) -> None:
        delete_template(tmp_path)
