"""Tests for vergil_tooling.lib.pr_template."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from vergil_tooling.lib.pr_template import (
    TemplateError,
    delete_template,
    read_template,
    write_template,
)

if TYPE_CHECKING:
    from pathlib import Path


class TestParseAndRead:
    def test_reads_simple_fields(self, tmp_path: Path) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        (vergil / "pr-template.yml").write_text(
            "issue: 42\n"
            "title: 'fix: bug'\n"
            "summary: Fix the bug\n"
            "linkage: Ref\n"
            "notes: Tested on macOS\n"
        )
        result = read_template(tmp_path)
        assert result["issue"] == "42"
        assert result["title"] == "fix: bug"
        assert result["summary"] == "Fix the bug"
        assert result["linkage"] == "Ref"
        assert result["notes"] == "Tested on macOS"

    def test_reads_double_quoted_values(self, tmp_path: Path) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        (vergil / "pr-template.yml").write_text(
            'issue: 42\n'
            'title: "feat(perms): restrict agent writes"\n'
            'summary: Restrict writes\n'
        )
        result = read_template(tmp_path)
        assert result["title"] == "feat(perms): restrict agent writes"

    def test_reads_multiline_block(self, tmp_path: Path) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        (vergil / "pr-template.yml").write_text(
            "issue: 42\n"
            "title: fix\n"
            "summary: |\n"
            "  Line one\n"
            "  Line two\n"
            "linkage: Ref\n"
        )
        result = read_template(tmp_path)
        assert result["summary"] == "Line one\nLine two"

    def test_skips_comment_lines(self, tmp_path: Path) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        (vergil / "pr-template.yml").write_text(
            "# Generated by agent\n"
            "issue: 42\n"
            "title: fix\n"
            "summary: Fix\n"
        )
        result = read_template(tmp_path)
        assert result["issue"] == "42"

    def test_raises_when_file_missing(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            read_template(tmp_path)

    def test_raises_when_required_field_missing(self, tmp_path: Path) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        (vergil / "pr-template.yml").write_text("issue: 42\ntitle: fix\n")
        with pytest.raises(TemplateError, match="summary"):
            read_template(tmp_path)


class TestWriteTemplate:
    def test_creates_vergil_dir_and_file(self, tmp_path: Path) -> None:
        path = write_template(
            tmp_path, issue="42", title="fix: bug", summary="Fix the bug"
        )
        assert path.exists()
        content = path.read_text()
        assert "issue:" in content
        assert "42" in content
        assert "fix: bug" in content

    def test_roundtrip(self, tmp_path: Path) -> None:
        write_template(
            tmp_path,
            issue="99",
            title="feat(auth): add token rotation",
            summary="Adds token rotation\nfor the GitHub App.",
            linkage="Ref",
            notes="Tested in staging VM.",
        )
        result = read_template(tmp_path)
        assert result["issue"] == "99"
        assert result["title"] == "feat(auth): add token rotation"
        assert "token rotation" in result["summary"]
        assert result["linkage"] == "Ref"
        assert result["notes"] == "Tested in staging VM."

    def test_warns_on_overwrite(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        (vergil / "pr-template.yml").write_text("old content")
        write_template(tmp_path, issue="42", title="fix", summary="Fix")
        err = capsys.readouterr().err
        assert "overwriting" in err.lower()

    def test_default_linkage(self, tmp_path: Path) -> None:
        write_template(tmp_path, issue="42", title="fix", summary="Fix")
        result = read_template(tmp_path)
        assert result["linkage"] == "Ref"


class TestDeleteTemplate:
    def test_deletes_existing_file(self, tmp_path: Path) -> None:
        vergil = tmp_path / ".vergil"
        vergil.mkdir()
        f = vergil / "pr-template.yml"
        f.write_text("content")
        delete_template(tmp_path)
        assert not f.exists()

    def test_no_error_when_missing(self, tmp_path: Path) -> None:
        delete_template(tmp_path)
