"""Read, write, and delete ``.vergil/pr-template.yml`` files.

Uses a minimal YAML-subset parser — no PyYAML dependency. Handles
flat ``key: value`` pairs, quoted values, and ``key: |`` multi-line
blocks. This is sufficient for the PR template format.
"""

from __future__ import annotations

import sys
from pathlib import Path

_TEMPLATE_DIR = ".vergil"
_TEMPLATE_FILE = "pr-template.yml"
_REQUIRED_FIELDS = ("issue", "title", "summary")


class TemplateError(Exception):
    """Raised when a template file is malformed or missing required fields."""


def _parse(text: str) -> dict[str, str]:
    """Parse the pr-template.yml format."""
    result: dict[str, str] = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value == "|":
            block_lines: list[str] = []
            i += 1
            while i < len(lines):
                if lines[i] and not lines[i][0].isspace():
                    break
                block_lines.append(
                    lines[i][2:] if len(lines[i]) > 2 else lines[i].strip()
                )
                i += 1
            result[key] = "\n".join(block_lines).strip()
        else:
            if len(value) >= 2 and value[0] in ("'", '"') and value[-1] == value[0]:
                value = value[1:-1]
            result[key] = value
            i += 1
    return result


def _template_path(worktree_root: Path) -> Path:
    return worktree_root / _TEMPLATE_DIR / _TEMPLATE_FILE


def read_template(worktree_root: Path) -> dict[str, str]:
    """Read and validate ``.vergil/pr-template.yml``.

    Raises ``FileNotFoundError`` if the file does not exist.
    Raises ``TemplateError`` if required fields are missing.
    """
    path = _template_path(worktree_root)
    if not path.exists():
        msg = f"No PR template found at {path}"
        raise FileNotFoundError(msg)
    fields = _parse(path.read_text())
    for field in _REQUIRED_FIELDS:
        if field not in fields:
            msg = f"PR template is missing required field: {field}"
            raise TemplateError(msg)
    return fields


def write_template(
    worktree_root: Path,
    *,
    issue: str,
    title: str,
    summary: str,
    linkage: str = "Ref",
    notes: str = "",
) -> Path:
    """Write ``.vergil/pr-template.yml``, warning if it already exists."""
    path = _template_path(worktree_root)
    if path.exists():
        print(
            f"WARNING: Overwriting existing PR template at {path}. "
            "A leftover template indicates a previous cycle was not completed.",
            file=sys.stderr,
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by agent — review and edit before running vrg-submit-pr",
    ]
    for key, value in [
        ("issue", issue),
        ("title", title),
        ("summary", summary),
        ("linkage", linkage),
        ("notes", notes),
    ]:
        if not value:
            continue
        if "\n" in value:
            lines.append(f"{key}: |")
            for vline in value.splitlines():
                lines.append(f"  {vline}")
        elif ":" in value or value.startswith(("'", '"')):
            lines.append(f'{key}: "{value}"')
        else:
            lines.append(f"{key}: {value}")
    path.write_text("\n".join(lines) + "\n")
    return path


def delete_template(worktree_root: Path) -> None:
    """Delete the template file if it exists."""
    path = _template_path(worktree_root)
    path.unlink(missing_ok=True)
