name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      run-security:
        type: boolean
        default: true
      run-release:
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-audit.yml@v1.5
    with:
      language: python
      versions: '["3.12", "3.13", "3.14"]'

  quality:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-quality.yml@v1.5
    with:
      language: python
      versions: '["3.12", "3.13", "3.14"]'
      container-tag: '3.14'
      container-suffix: python

  security:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-security.yml@v1.5
    permissions:
      contents: read
      security-events: write
    with:
      language: python
      run-standards: ${{ inputs.run-release != 'false' }}
      run-security: ${{ inputs.run-security != 'false' }}
      container-tag: '3.14'
      container-suffix: python

  test:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-test.yml@v1.5
    with:
      language: python
      versions: '["3.12", "3.13", "3.14"]'

  version:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-version-bump.yml@v1.5
    with:
      language: python
      run-release: ${{ inputs.run-release != 'false' }}
      container-tag: '3.14'
      container-suffix: python
