name: Ops

on:
  schedule:
    - cron: '15 6 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  github-config:
    uses: vergil-project/vergil-actions/.github/workflows/ops-github-config.yml@v1.5
    permissions:
      contents: read
      issues: write
